import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerBrowserNavigate } from './browser-navigate.js';
import { registerBrowserClick } from './browser-click.js';
import { registerBrowserType } from './browser-type.js';
import { registerBrowserEvaluate } from './browser-evaluate.js';
import { registerBrowserMarkdown } from './browser-markdown.js';
import { registerBrowserLinks } from './browser-links.js';
import { registerBrowserSnapshot } from './browser-snapshot.js';
import { registerBrowserInteractiveElements } from './browser-interactive-elements.js';
import { registerBrowserConsoleMessages } from './browser-console-messages.js';
import { registerBrowserNetworkRequests } from './browser-network-requests.js';
import { registerBrowserErrors } from './browser-errors.js';
import { registerBrowserPressKey } from './browser-press-key.js';
import { registerBrowserSelectOption } from './browser-select-option.js';
import { registerBrowserWaitFor } from './browser-wait-for.js';
import { registerBrowserScroll } from './browser-scroll.js';
import { registerBrowserStatus } from './browser-status.js';
import { registerBrowserCookies } from './browser-cookies.js';
import { registerBrowserAccessibility } from './browser-accessibility.js';
import { registerBrowserDomQuery } from './browser-dom-query.js';
import { registerBrowserDebugReport } from './browser-debug-report.js';
import { registerScrapePage } from './scrape-page.js';
import { registerScrapeBatch } from './scrape-batch.js';
import { registerExtractData } from './extract-data.js';

export function registerAllTools(server: McpServer): void {
  registerBrowserNavigate(server);
  registerBrowserClick(server);
  registerBrowserType(server);
  registerBrowserEvaluate(server);
  registerBrowserMarkdown(server);
  registerBrowserLinks(server);
  registerBrowserSnapshot(server);
  registerBrowserInteractiveElements(server);
  registerBrowserConsoleMessages(server);
  registerBrowserNetworkRequests(server);
  registerBrowserErrors(server);
  registerBrowserPressKey(server);
  registerBrowserSelectOption(server);
  registerBrowserWaitFor(server);
  registerBrowserScroll(server);
  registerBrowserStatus(server);
  registerBrowserCookies(server);
  registerBrowserAccessibility(server);
  registerBrowserDomQuery(server);
  registerBrowserDebugReport(server);
  registerScrapePage(server);
  registerScrapeBatch(server);
  registerExtractData(server);
}
